language: python


python:
    - "3.5"


env:
    - DJANGO_SETTINGS_MODULE=NTHU_Course.settings.testing_sqlite


install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install flake8


before_script:
    - flake8 --exclude=const.py .
    - ./manage.py makemigrations
    # we have to do this because migrations are currently not tracked by git


script:
    - sh ./test.sh


notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/70c147dedbec7df5429e
        on_success: always
        on_failure: always
        on_start: false
