language: python


python:
    - "2.7"


install:
    - pip install --upgrade pip
    - pip install -r requirement.txt
    - pip install pep8
    - pip install pyflakes


before_script:
    - pyflakes .
    - pep8 --exclude=const.py

script:
    - sh ./test.sh


notifications:
    email:
        recipients:
            - z54981220@gmail.com
            - henryyang42@gmail.com
        on_failure: always

